<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Calcula</name>
   <tag></tag>
   <elementGuidId>0d26214d-5869-4ef1-8621-a4b40af40132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cifra_control_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifra_control_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd0a1dc2-d069-405d-b1e3-f5097903c516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-info</value>
      <webElementGuid>a4aa375a-8497-4c73-aac2-d6bfb1c2b346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifra_control_btn</value>
      <webElementGuid>7594d453-1d59-4554-83bf-87cfe58c306d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calcula </value>
      <webElementGuid>f83b8bc6-c33a-4e54-8647-c1882eda5f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifra_control_btn&quot;)</value>
      <webElementGuid>cfcd434d-a67a-414e-8dcd-afaf464b5a9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cifra_control_btn']</value>
      <webElementGuid>92fce0ed-9760-4667-9266-a49f93082fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los 8 primeros caracteres del NIF/NIE'])[1]/following::button[1]</value>
      <webElementGuid>d80891eb-a031-477b-8c39-da0a47c0028b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcula dígito de control NIF/NIE'])[1]/following::button[1]</value>
      <webElementGuid>a18d2a34-0f2c-4f55-be21-185ef461b13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcula dígito de control CIF'])[1]/preceding::button[2]</value>
      <webElementGuid>e24e5be6-f9c6-43f1-a8ae-e1e027504d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los 8 primeros caracteres del CIF'])[1]/preceding::button[2]</value>
      <webElementGuid>b26eedae-bfcf-4ab2-a982-93c3de2731f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calcula']/parent::*</value>
      <webElementGuid>ac4a1388-0832-446e-8369-2c400fe36b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div[2]/div/button</value>
      <webElementGuid>f44cead3-2230-4df5-aafe-8a020001e586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cifra_control_btn' and (text() = 'Calcula ' or . = 'Calcula ')]</value>
      <webElementGuid>c6262fdb-e1a3-41d7-99b8-92637b05df06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
