<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CIF</name>
   <tag></tag>
   <elementGuidId>c2ae87f6-16f0-49f4-9f6d-4c5f92ac5e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7643966c-d62e-45db-b80d-db19112c3a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-outline-info btn-block pull-right</value>
      <webElementGuid>1c41a2eb-64ae-40eb-8fb1-fb9348f0588b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cif</value>
      <webElementGuid>f4ac296d-edce-4b4e-9b34-0eb72cb0f518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                CIF 
                            </value>
      <webElementGuid>febceee6-a3ec-4a7c-9387-86f4f16c96bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cif&quot;)</value>
      <webElementGuid>35c408dd-d0a4-4d97-82fd-ab7840ddd806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cif']</value>
      <webElementGuid>fb4f2d12-fe57-44db-9532-b13beaffe7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C10851814'])[1]/following::button[1]</value>
      <webElementGuid>e65b81b2-0f34-4213-8f1e-778f05c3af49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número CIF'])[1]/following::button[1]</value>
      <webElementGuid>8e4f50c8-be73-44f6-845c-42216eb6ac5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C10851814'])[2]/preceding::button[1]</value>
      <webElementGuid>861922f2-2df3-46cd-a9f6-88f96659b0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CIF']/parent::*</value>
      <webElementGuid>325b112c-79da-4e28-bd30-0786642968e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>feb5be8f-06cd-453d-b7a8-a7176a5c2c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cif' and (text() = '
                                CIF 
                            ' or . = '
                                CIF 
                            ')]</value>
      <webElementGuid>27b9aa29-f500-404b-9471-a758c2dada5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
