<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NIE</name>
   <tag></tag>
   <elementGuidId>9b6b9029-440a-4b5b-ac23-a1101b49615a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>410b4f6a-aa2e-4dc7-b064-acb42f1715d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-outline-info btn-block pull-right</value>
      <webElementGuid>db296792-7a52-47fe-90c9-6efb6ce3c525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nie</value>
      <webElementGuid>e7c9246f-7282-4ef0-b4de-3750a5126515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                NIE 
                            </value>
      <webElementGuid>00ccf2c5-9de9-4b53-830d-6d0075af87da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nie&quot;)</value>
      <webElementGuid>1bdf927c-1317-4413-bcc9-10d3d4c76709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nie']</value>
      <webElementGuid>1b238fd1-4c54-441a-9648-84dfc20498ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y1060550B'])[1]/following::button[1]</value>
      <webElementGuid>0717564b-4685-463f-9f66-b83ad9b1cfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número NIE'])[1]/following::button[1]</value>
      <webElementGuid>59fb6e3d-fee1-4a94-b2c9-3425b69f9ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y1060550B'])[2]/preceding::button[1]</value>
      <webElementGuid>d3e39ea3-f2c5-4821-a5c5-a38fc0d5adea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NIE']/parent::*</value>
      <webElementGuid>d8e46d62-7c68-4066-ae0f-b1170a13d5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>e860131a-2d1f-45cb-a643-36ab130af3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nie' and (text() = '
                                NIE 
                            ' or . = '
                                NIE 
                            ')]</value>
      <webElementGuid>ce24c254-4a2e-44b2-95d4-ab7ac5252293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
