<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Valida</name>
   <tag></tag>
   <elementGuidId>ca7f18c1-7f2a-44ad-a32d-6c271726561b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='valida_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#valida_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b4d3cad-fd87-4b9a-949a-306ee71e4ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-info</value>
      <webElementGuid>7d6ddda5-aae2-4df2-9c81-6a84877c2383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>valida_btn</value>
      <webElementGuid>48c30bc1-88f6-48e5-8671-2519ea79325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valida </value>
      <webElementGuid>2360a15b-a465-442e-9b9d-2bac1cd080ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;valida_btn&quot;)</value>
      <webElementGuid>4ebcd396-2469-46ff-9bd5-6d75ad214e98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='valida_btn']</value>
      <webElementGuid>1da966dc-9a02-40a9-a1c7-0b9c1acb49a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valida NIF, NIE, CIF'])[1]/following::button[1]</value>
      <webElementGuid>9bbc8fc6-dd8a-4c14-a3f8-d1356c7bcfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valida y calcula'])[1]/following::button[1]</value>
      <webElementGuid>7c49723d-8d7e-4566-9773-db9b1fea6125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcula dígito de control NIF/NIE'])[1]/preceding::button[2]</value>
      <webElementGuid>bf53138a-f018-4b81-b6b2-989c3542d648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los 8 primeros caracteres del NIF/NIE'])[1]/preceding::button[2]</value>
      <webElementGuid>3ebffaef-caea-4ff9-b7f2-3f3a2b6835ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Valida']/parent::*</value>
      <webElementGuid>40104be2-b6d6-4fef-97d6-15960c2a53ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>32cf4c1d-882e-4409-b2b4-ce497c90611a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'valida_btn' and (text() = 'Valida ' or . = 'Valida ')]</value>
      <webElementGuid>34270515-5a50-4011-8711-c2f83586ccf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
