<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_CIF_svg-inline--fa fa-redo fa-w-16</name>
   <tag></tag>
   <elementGuidId>c6b77736-0b71-4ed7-9b97-9be96b4ff13b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='CIF'])[3]//*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifra_control_cif_btn > svg.svg-inline--fa.fa-redo.fa-w-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>44eb6000-b4a3-4f75-b6eb-072e8beca73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-redo fa-w-16</value>
      <webElementGuid>203469b9-3e40-46e4-a6c8-50b924da6215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1914b2c-af36-4ac6-b21e-6201eab81795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5960c169-a216-4f4f-929b-d507c07a3c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fa</value>
      <webElementGuid>92429123-cada-4339-a6b8-bdcfb93a3146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>redo</value>
      <webElementGuid>c7123e89-ed51-4c27-b646-9031f92af7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da23c868-d5f9-4e74-bf9d-65dbc0c3d68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d5b3e4c0-361d-4bc6-9823-cb72baadc8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
      <webElementGuid>12da1f1c-529f-4e17-a583-191bbdb44afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifra_control_cif_btn&quot;)/svg[@class=&quot;svg-inline--fa fa-redo fa-w-16&quot;]</value>
      <webElementGuid>8df3f235-49a8-490e-85f7-5a93389b9e1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIF'])[3]//*[name()='svg'][1]</value>
      <webElementGuid>ba6fa036-5841-4b1a-8294-edcd3a8fdf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Los 8 primeros caracteres del CIF'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0f094df0-ad34-4a34-9a07-e8f115f111d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy me a coffee'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>5b2eb06a-2326-4373-92f0-d6bfa16cf3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algoritmo de generación'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>69cedd67-f7c0-4489-a317-9784aac5bb22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
