<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N contrato_searchAgreementAgreementNumber</name>
   <tag></tag>
   <elementGuidId>c77a8c82-0019-4f2b-aed9-d33576b675dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-agreement-agreementNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-agreement-agreementNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81b56915-9d19-4efe-a731-82d2b219d312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-agreement-agreementNumber</value>
      <webElementGuid>ff16ec7e-1de0-418f-8548-a93b9b764d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchAgreementAgreementNumber</value>
      <webElementGuid>db863e0d-39f6-44a8-8d32-5e3ef7cc904c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.agreementCriteria.agreementNumber</value>
      <webElementGuid>a889bbd2-4d6f-4060-82be-837aca12004d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>longField ng-pristine ng-untouched ng-valid ng-valid-rci-joker-min-length ng-valid-maxlength</value>
      <webElementGuid>dd93f78e-636f-451e-a8ce-e847dcec8728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>542b67d0-1951-4056-8f2f-35a9bb517b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>d06f15e1-6ebc-4bfe-b473-a90904e69d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rci-joker-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>13696c95-29c8-456c-a07d-b6f6ad002479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-agreement-agreementNumber&quot;)</value>
      <webElementGuid>ad520bf8-8247-4fd2-bdec-6186e9d83f40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-agreement-agreementNumber']</value>
      <webElementGuid>9ca683f0-d586-43d0-8054-8809d7390f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workspace']/div[2]/rci-search-agreement/div/rci-include-section/div/div/div/form/div/div[3]/input</value>
      <webElementGuid>4c4e6235-6d27-43f2-81fc-abdc93098c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b7d0cdfe-48c3-4c70-abca-94a83cd1ec48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-agreement-agreementNumber' and @name = 'searchAgreementAgreementNumber' and @type = 'text']</value>
      <webElementGuid>17924e8d-a7da-45b4-8d0b-6e62d8af488e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
