<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Seleccion version</name>
   <tag></tag>
   <elementGuidId>ad68d0a8-fba6-4df0-a145-58bcde064534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mycombobox-1700-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycombobox-1700-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a9a3235-03f5-42ce-890f-48d87df57af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycombobox-1700-inputEl</value>
      <webElementGuid>b0c32ad2-8579-4196-9f2e-79c72be469de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70c23ec5-2000-43e1-8cc0-7f228cf8fc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-trigger-noedit x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>703156dd-50d3-4c2e-9f79-adbf9a3344d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0ddbac1-dbc5-425f-b202-a9a761866ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>version</value>
      <webElementGuid>0d0b263a-b86b-4479-8e57-6e332e79ec99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8db03675-d46e-43e5-9dda-03c26c33363d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycombobox-1700-inputEl&quot;)</value>
      <webElementGuid>ab0daad5-2636-41a3-b739-a37081778324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mycombobox-1700-inputEl']</value>
      <webElementGuid>b4556164-b36c-4657-a2f5-e9fa61c8e621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='mycombobox-1700-inputCell']/input</value>
      <webElementGuid>c25182a5-0a7b-4291-9c81-056827b22079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>91d9da45-6eb0-4147-ac16-edf73c81f830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mycombobox-1700-inputEl' and @type = 'text' and @name = 'version']</value>
      <webElementGuid>4424c7d6-5fec-4497-ad7a-85064a403828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
