<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Seleccion diesel</name>
   <tag></tag>
   <elementGuidId>d43f5a63-50f2-46a2-bed7-0ab921e7efd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mycombobox-1699-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycombobox-1699-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb3a29db-9348-4460-84f8-d3500f9eb61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ef947f9a-d79a-48b2-87a2-9e247b55abb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b24c7dbc-2f05-4a75-98f0-68908afe7cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-trigger-noedit x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>aa340af5-5fd8-4ad5-bbff-d92778f53829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIESEL</value>
      <webElementGuid>86850ddd-53d8-420d-ad61-280091c2999f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycombobox-1699-inputEl&quot;)</value>
      <webElementGuid>801b86a4-b7a4-4895-a75a-62b8ef9cde11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycombobox-1699-inputEl</value>
      <webElementGuid>afdcccc1-bca0-4a6c-b385-912ae5a26217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>763e2943-fe13-46a3-a0d6-e12258a85b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>035ea72c-3867-4c13-a949-a86858d60afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carburante</value>
      <webElementGuid>9f2725d2-15df-4941-81fb-07c73bb25f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>0f8a4333-4b1b-4554-ae50-cc1c9b6c14e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7a13fc0-c79e-42fb-b10f-2b56b9bacc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mycombobox-1699-inputEl']</value>
      <webElementGuid>c098c9ba-1554-4e1a-8550-d6eab4f82773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='mycombobox-1699-inputCell']/input</value>
      <webElementGuid>7eab67a6-8791-4172-b054-1384c4bade5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>2a010a2c-06ef-49d8-8d0a-d2f0b8135ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mycombobox-1699-inputEl' and @type = 'text' and @name = 'carburante']</value>
      <webElementGuid>799d3770-2d6c-4a4b-bd37-2692aa862b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boundlist-1866-listEl']/ul/li[2]</value>
      <webElementGuid>efd0154d-2ca0-4032-abbb-f2ab8e018130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GASOLINA'])[1]/following::li[1]</value>
      <webElementGuid>500b8fc7-20e2-41b6-be84-2f65bc8c3b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::li[2]</value>
      <webElementGuid>2d35ebf4-649f-493a-abde-de5e73d41f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECTRICO BL'])[1]/preceding::li[1]</value>
      <webElementGuid>c67d16c0-8644-44ed-9a37-298a94f8e032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECTRICO FULL PURCHASE'])[1]/preceding::li[2]</value>
      <webElementGuid>aefaa7d9-7dd8-434e-9edb-a31b9c6f5aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIESEL']/parent::*</value>
      <webElementGuid>c489219d-108a-44e1-8d9e-9eb39f4e6bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>15088e34-fe6d-4a8f-907f-bcac2b0b1732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'DIESEL' or . = 'DIESEL')]</value>
      <webElementGuid>22c28eb8-213d-4afb-9439-4356daed0187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
