<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SOLICITUDES_button-1068-btnIconEl</name>
   <tag></tag>
   <elementGuidId>de7fea90-b4ce-45e5-8b13-6bf40322cac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1068-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1068-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11905820-3da4-420a-b4cc-2accc753e7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1c67cc57-d65e-4058-8c30-abb2d2a7565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1068-btnIconEl</value>
      <webElementGuid>1b7a84e6-15e5-40d3-be45-5aafd5be5bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>41f26c3e-183b-499d-bcbf-6e08433900d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>0547fdd6-3a67-4839-9309-5d6172c111d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1068-btnIconEl&quot;)</value>
      <webElementGuid>fbd034ef-d4d1-493d-8b0f-f81d0f00053e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1068-btnIconEl']</value>
      <webElementGuid>122c7659-2d26-40cd-96bb-9dd5bc78bb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1068-btnEl']/span[2]</value>
      <webElementGuid>7b3aa40b-1b1d-45ff-9a14-2083d1661a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]/span/span/span[2]</value>
      <webElementGuid>fee1ca0d-e78d-45f6-a2e7-a8cb2a3f3561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1068-btnIconEl']</value>
      <webElementGuid>a6fa50f9-25cb-4581-8542-dc2bf32a1746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
