<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Buscar</name>
   <tag></tag>
   <elementGuidId>61eeea24-a6d8-43f3-9a66-86d5e392c40d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1733-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1733-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ffddaa9b-df34-4ccb-a453-3e4786d1e436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1733-btnInnerEl</value>
      <webElementGuid>31c88c9f-ca4d-4923-9bac-7cf334eda98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-center</value>
      <webElementGuid>d7aa5711-7b17-4108-8c13-7524d6dd03cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>cf16605a-a12c-457e-b7bf-5fac64be3e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buscar</value>
      <webElementGuid>e7d42fde-8fc5-4915-b4de-e6ecb6d0faf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1733-btnInnerEl&quot;)</value>
      <webElementGuid>5b9feff2-3279-41f9-a258-4a7aad8e3e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1733-btnInnerEl']</value>
      <webElementGuid>32fb485b-55c7-4ff5-b1f1-661b874ea079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1733-btnEl']/span</value>
      <webElementGuid>b563da0c-2722-4814-bf9c-5ba22a1c3442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/following::span[4]</value>
      <webElementGuid>476fb465-bc23-4087-823f-26ddab96d429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T. ACTIVIDAD'])[2]/following::span[7]</value>
      <webElementGuid>78f039d1-19f3-4f05-a043-1852656034dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados'])[1]/preceding::span[2]</value>
      <webElementGuid>823b861e-d7af-4a81-a23e-b1fa0f52e3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='verif'])[1]/preceding::span[4]</value>
      <webElementGuid>783e8c07-35e5-4364-9bf6-fca9a8e9c289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buscar']/parent::*</value>
      <webElementGuid>379893d9-896e-4f59-ac58-b70381929320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/a[2]/span/span/span</value>
      <webElementGuid>e73ea4fa-dd4e-4c88-8eb2-eb03483a527e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1733-btnInnerEl' and (text() = ' Buscar' or . = ' Buscar')]</value>
      <webElementGuid>4a6e4a33-656e-4c0d-8d73-a9fc96b7a895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
