<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_UNISONO_button-1668-btnIconEl</name>
   <tag></tag>
   <elementGuidId>84587d3a-ef0b-495d-854b-ce0f2b2883eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1668-btnIconEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1668-btnIconEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b82d8a24-ab97-481d-ba34-5fd6b984964a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>81b0d9f0-87da-4fa1-8f51-0d27af5fbca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1668-btnIconEl</value>
      <webElementGuid>686f4539-27ca-4d2f-b03f-2444bb28ddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>9775cd87-9a4a-4970-955c-4434fe09f688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>ed11d7cd-b4ce-4baa-b75c-589506d0c5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1668-btnIconEl&quot;)</value>
      <webElementGuid>d8ec4d82-0469-421b-9454-534376e86c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1668-btnIconEl']</value>
      <webElementGuid>8494d1f1-7155-40c3-a4eb-dead8dbe1612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1668-btnEl']/span[2]</value>
      <webElementGuid>9ac8565a-bd6c-4818-82be-1328b21352e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span/span/span[2]</value>
      <webElementGuid>cfd95a42-ae5b-4f33-8161-fb433dd1b4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1668-btnIconEl']</value>
      <webElementGuid>408e0e0c-4753-49b8-abc5-8ebc6663bf51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
