<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_4815884</name>
   <tag></tag>
   <elementGuidId>22b56be2-cba6-4b44-ac37-86231a5e99c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.data</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='label-2350']/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2237a5f0-f9b4-4ed2-9266-520dc8c88925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>de6c1dea-4807-4f7a-b33c-8db01d1be214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4815884</value>
      <webElementGuid>1a86ff1c-6626-4957-ace8-968a42081ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label-2350&quot;)/table[@class=&quot;tbl-info-detalle-sol&quot;]/tbody[1]/tr[1]/td[@class=&quot;data&quot;]</value>
      <webElementGuid>60e197e8-c168-4bc7-8e55-5e5905993bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='label-2350']/table/tbody/tr/td[2]</value>
      <webElementGuid>86119c4e-9811-49fa-a686-c52134777856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud:'])[1]/following::td[1]</value>
      <webElementGuid>cc3ae395-32a6-4b52-9bd9-28b1ef47e559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Espere por favor...'])[1]/following::td[2]</value>
      <webElementGuid>91d3e4ca-17d8-4cdf-b407-06daaf2410bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado:'])[1]/preceding::td[1]</value>
      <webElementGuid>a5e37e03-c160-4d8e-9fd1-3c503128aa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acep. Pendiente documentacion'])[1]/preceding::td[2]</value>
      <webElementGuid>d064a172-0268-4b3a-a27d-74599836ba12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/table/tbody/tr/td[2]</value>
      <webElementGuid>0b36dd10-b9e1-4a63-adf1-4aae8a46f5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '4815884' or . = '4815884')]</value>
      <webElementGuid>6dbf71e6-7e41-407c-b5de-7f00404b6b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
