<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>combo modelo</name>
   <tag></tag>
   <elementGuidId>dd89313f-7058-4489-8779-0f116fac7c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mycombobox-1698-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycombobox-1698-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0f1d769-12eb-4134-bc92-46ce47f95d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycombobox-1698-inputEl</value>
      <webElementGuid>a52ccf79-e799-4c96-bd61-556ce26889a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8716d5f-6e06-4eb9-8e45-b187994e0893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-trigger-noedit x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>b59566cb-8ae2-4e79-8780-1dad2577b5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a2202603-9d8e-42e3-b914-2a0704a5fa87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modelo</value>
      <webElementGuid>8fe3ada8-b95e-492b-8270-5c1ab6377f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>0eb53bb0-3db2-48c3-9576-a9207f0db937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>140151bf-8aa1-4a55-8752-8a020544d622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycombobox-1698-inputEl&quot;)</value>
      <webElementGuid>53dcab38-7b50-4b6c-83d0-901d4585a548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mycombobox-1698-inputEl']</value>
      <webElementGuid>e043bb44-5744-4b22-bcf7-d99f9dc73a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='mycombobox-1698-inputCell']/input</value>
      <webElementGuid>e2c550f1-b43f-4e96-95f0-f68a75567ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/table[3]/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>1b68f9f2-245a-4ec5-a766-03ed5f88b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mycombobox-1698-inputEl' and @type = 'text' and @name = 'modelo']</value>
      <webElementGuid>40cd8012-aaab-4c9a-ab42-a87c8076b9f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
