<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_DIESEL</name>
   <tag></tag>
   <elementGuidId>589b07f0-85a5-493f-86f2-a6be7b6a9844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='boundlist-1868-listEl']/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycombobox-1699-inputEl
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ce4f683a-01ed-4c63-9751-60c419309f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>597c27dc-be88-4455-b6cb-b80cd46b9a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>962d883d-6876-45ca-a0c5-017ec435121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-selected x-boundlist-item-over</value>
      <webElementGuid>3f4b6629-9851-49a3-bd5f-ee9da9a87d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIESEL</value>
      <webElementGuid>7e6f7325-e7f3-4fab-8bbd-860efe938875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boundlist-1868-listEl&quot;)/ul[@class=&quot;x-list-plain&quot;]/li[@class=&quot;x-boundlist-item x-boundlist-selected x-boundlist-item-over&quot;]</value>
      <webElementGuid>84d01dd6-8ae5-4d80-87dc-07b7745c7ed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boundlist-1868-listEl']/ul/li[2]</value>
      <webElementGuid>021026a9-a45a-43fb-a678-6339dd2b6bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GASOLINA'])[1]/following::li[1]</value>
      <webElementGuid>e2806f55-95d0-4ee8-b37b-c1bcaed90dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZO1 - MEGANE E-TECH ELECTRICO'])[1]/following::li[3]</value>
      <webElementGuid>a130fdd3-6d60-4c77-8bb0-153cd75d0026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECTRICO BL'])[1]/preceding::li[1]</value>
      <webElementGuid>3a89a040-69a1-4d5d-8667-e1575ff981d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ELECTRICO FULL PURCHASE'])[1]/preceding::li[2]</value>
      <webElementGuid>7a44c5e7-dd4c-4fec-bab3-5df6671ca0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIESEL']/parent::*</value>
      <webElementGuid>568f0bec-1f5b-4fc4-8796-743812d9f5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/ul/li[2]</value>
      <webElementGuid>709462fc-3100-4998-a475-61c10a2908bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'DIESEL' or . = 'DIESEL')]</value>
      <webElementGuid>5d94d96b-cb3a-49f9-bcd7-cb68349cb085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boundlist-1866-listEl']/ul/li[2]</value>
      <webElementGuid>9c1c0612-e6ec-4af5-9c43-d707c284820a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::li[2]</value>
      <webElementGuid>cd70bd12-c407-40c7-b905-4d298005e9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>282740b0-87b8-4de6-9179-0cd73a77b4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
