<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Seleccion de Red</name>
   <tag></tag>
   <elementGuidId>0fabe12a-b00a-45f7-923a-d7df9dff098d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mycombobox-1092-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycombobox-1092-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afbdae9e-f10a-401a-829e-8674640f8f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycombobox-1092-inputEl</value>
      <webElementGuid>d2660b71-347b-4575-a8ca-25096667b9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34ba4545-4bdd-4ce5-a1c8-13567dd3807c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-form-focus x-field-form-focus x-field-default-form-focus</value>
      <webElementGuid>58ff9831-1fd8-47ee-b7ff-5a2f67bbd91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd6abc68-8cbe-4054-a39f-d061fb964c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycombobox-1092-inputEl</value>
      <webElementGuid>001a3882-1b3a-4383-822d-fbde4d9bedb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Seleccione Punto de Red/Proveedor...</value>
      <webElementGuid>3791a546-8979-4836-8e57-75aa68c7eb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d94d1f6e-9943-4dbe-bd7b-e5213382d473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycombobox-1092-inputEl&quot;)</value>
      <webElementGuid>486b9cf3-da69-45d1-b217-837c3d382050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mycombobox-1092-inputEl']</value>
      <webElementGuid>0d65be37-96a7-44a1-aea6-254a84b40f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='mycombobox-1092-inputCell']/input</value>
      <webElementGuid>ceefa608-7953-4eea-aad3-7c368f8736fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7b1301fa-098b-4da9-8e1a-f2f10dcaec5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mycombobox-1092-inputEl' and @type = 'text' and @name = 'mycombobox-1092-inputEl' and @placeholder = 'Seleccione Punto de Red/Proveedor...']</value>
      <webElementGuid>866bbbad-eadc-4a78-bdb6-77f86da3f006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
