<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PRODUCCIONENTRAR</name>
   <tag></tag>
   <elementGuidId>41e98e56-9c5c-48d7-be4d-f40ecde38ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='abox4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abox4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f351baa9-22d7-4603-a54a-98a98f67efbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abox4</value>
      <webElementGuid>9f748269-60e2-4830-8584-dfb82a97cc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a76d2d75-369f-4832-8a7d-4da86164cb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clickBotonMenu(this)</value>
      <webElementGuid>655ba1a6-cf19-472a-83b4-653651cc25d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle</value>
      <webElementGuid>cb083e6a-52b2-4af0-8cd0-afdf058275a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noapp</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ef429a13-5036-4f18-83f9-7c2b8a3db57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRODUCCIONENTRAR</value>
      <webElementGuid>4fd8b6b7-e126-4100-a620-21c9d1685896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abox4&quot;)</value>
      <webElementGuid>1cd7b607-c2b6-482e-8c86-8d9195bdfed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='abox4']</value>
      <webElementGuid>65d82807-82b1-4850-ac37-ef7b5253d626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divapp4']/a</value>
      <webElementGuid>93abf3ea-1bcb-46ae-8eb7-35ce4d8f1930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTRAR'])[5]/following::a[1]</value>
      <webElementGuid>286f4dca-373d-46b4-9ff1-b5ee55854bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEGURO AUTO'])[2]/following::a[1]</value>
      <webElementGuid>3ecd7b55-cc50-47f5-8f61-c0ff8cb354fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>061ddedc-0225-4798-a531-f9a2769dd833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/a</value>
      <webElementGuid>a3e138b7-f018-41c1-8310-a3234157ed0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'abox4' and @href = '#' and (text() = 'PRODUCCIONENTRAR' or . = 'PRODUCCIONENTRAR')]</value>
      <webElementGuid>3ea58052-b585-4c46-8840-e09a4699b4d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
