<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SOLICITUDESENTRAR</name>
   <tag></tag>
   <elementGuidId>d5d5ab40-48e1-4d05-8f40-28481845774f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#abox2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='abox2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76624e5c-964b-4613-97f6-ed2d0cb820a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abox2</value>
      <webElementGuid>d5c0367f-8516-491b-a22b-a60e267e3b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>753d337c-61b6-4862-9a01-0193c16fdbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clickBotonMenu(this)</value>
      <webElementGuid>4e26af1b-adfd-42eb-b731-a71d8e9e2944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle</value>
      <webElementGuid>e9b2fada-4d19-45ea-b238-d80ce5eb324b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noapp</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0060c826-47f8-4856-a000-652e4784f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SOLICITUDESENTRAR</value>
      <webElementGuid>29ffa6f2-f31c-458b-9d01-bce6f2a0814f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abox2&quot;)</value>
      <webElementGuid>3d0852fc-4bc3-44df-82b3-aac13654cc81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='abox2']</value>
      <webElementGuid>6d967230-4bc4-49f8-bcb0-f092eb187f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divapp2']/a</value>
      <webElementGuid>0027625d-e206-44bc-8810-bbb53581210d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTRAR'])[2]/following::a[1]</value>
      <webElementGuid>6f589704-eefb-47a4-92d3-e9637f4068d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN. USUARIOS'])[2]/following::a[1]</value>
      <webElementGuid>ed1bab3b-821a-4e27-bc19-9fb4c906cb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>40e07b9d-df72-4c19-b332-ecd2769a0d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/a</value>
      <webElementGuid>f53f8cce-0708-45b1-9bae-c2fd66d1ec69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'abox2' and @href = '#' and (text() = 'SOLICITUDESENTRAR' or . = 'SOLICITUDESENTRAR')]</value>
      <webElementGuid>071032a9-d76b-40c0-bb60-6e9cdc6f6e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
