<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>objetBaremos</name>
   <tag></tag>
   <elementGuidId>053ae9b7-b3ca-4be8-99bb-892c47ae3ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1667</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1667']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f210993d-a714-4333-a72e-2f0df2596ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-component-default</value>
      <webElementGuid>db15cd95-a730-4c45-a67f-dd5c92ce72fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1667</value>
      <webElementGuid>a823c543-177b-4dbd-9d55-d87e1b1d9a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://rcieslv01.grouperci.com:60360/Baremos/baremosExt/index.jsp?ipn=PS13116&amp;locale=es-ES</value>
      <webElementGuid>10483ef5-c3d4-4aae-8ffb-a7f1d7f7d9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1667&quot;)</value>
      <webElementGuid>0b47a2de-7b1b-4348-8817-88c39a0b0c30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1667']</value>
      <webElementGuid>550b51d7-6153-4a03-a39e-e6b6f26f5182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containeriframe-1666-innerCt']/iframe</value>
      <webElementGuid>7e885475-9dab-4951-ba83-39988a670859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c3065618-90fe-4b85-b4fa-84c70ffd9444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1667' and @src = 'http://rcieslv01.grouperci.com:60360/Baremos/baremosExt/index.jsp?ipn=PS13116&amp;locale=es-ES']</value>
      <webElementGuid>c75bbfe7-2226-4a16-9bba-6230bdf9084e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
