<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buscar operacin_idOperation</name>
   <tag></tag>
   <elementGuidId>f59defa4-f9a1-4ef3-8252-9916eee96723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myTextField-1701-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#myTextField-1701-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>441c6067-a8fe-44af-882e-2b7ce5771a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myTextField-1701-inputEl</value>
      <webElementGuid>96f9c6f8-40ea-4bff-8bc4-9e3a5f8cc297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b368e7fe-f623-419e-a691-7872353b2a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>idOperation</value>
      <webElementGuid>4298abd6-4e8b-4ea3-a902-c74fbe5649fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-text x-tfBaseFocus x-field-tfBaseFocus x-field-default-tfBaseFocus</value>
      <webElementGuid>9aef1014-1829-4821-a266-3be47822defa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e2fde439-d9a6-4d02-a3a2-3deb0895eb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e69354c-19e6-45ed-a4bb-7ddd4bd26706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTextField-1701-inputEl&quot;)</value>
      <webElementGuid>2dc1223c-bf84-423a-a1be-d14f6fa74acc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myTextField-1701-inputEl']</value>
      <webElementGuid>f929f938-6966-4641-b9df-5fdf5d2bd54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='myTextField-1701-bodyEl']/input</value>
      <webElementGuid>ae84bdac-0782-4340-b5a8-eeddaabf5f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td[2]/input</value>
      <webElementGuid>824a1485-0195-427f-9bf6-eb047513696a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'myTextField-1701-inputEl' and @type = 'text' and @name = 'idOperation']</value>
      <webElementGuid>5cd9d42e-bf1e-48cf-9ce9-0168c5d47480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
