<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fraude_button-2381-btnIconEl</name>
   <tag></tag>
   <elementGuidId>eab2f140-c144-4dc7-a2bf-7049741ca74c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-2381-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-2381-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e33e2f61-715f-4c6a-beb8-a42b8d49ac5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ccf35eb-3ece-49ee-b812-4a8fa56abfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-2381-btnIconEl</value>
      <webElementGuid>3f4c0abe-93b8-4fca-8bd8-65d8578ee89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>0ea8ee9b-e30f-443d-bc9a-9ef86b9f847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>eab068b6-62c2-4709-ae38-948b3c8b7417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-2381-btnIconEl&quot;)</value>
      <webElementGuid>6332e434-3983-4d8a-83f9-a95abaccd2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-2381-btnIconEl']</value>
      <webElementGuid>71bfa2a0-bb10-4ec4-97e6-c81b3caa48f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-2381-btnEl']/span[2]</value>
      <webElementGuid>5e01d8d7-cfd1-4249-97d6-3b3371f3e5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/a[4]/span/span/span[2]</value>
      <webElementGuid>07bffd81-410f-4fd0-87cb-f892f143cdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-2381-btnIconEl']</value>
      <webElementGuid>034449fa-82f3-499a-b844-94ab8ff2d5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
