<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X - Cerrar_button-4115-btnIconEl</name>
   <tag></tag>
   <elementGuidId>db8e1cc9-8494-4297-8db3-699779163c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-4115-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-4115-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38928dcc-799a-4094-b862-4f9ecd918865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9d8f3dd6-fd30-4824-869e-e23ecccf20fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-4115-btnIconEl</value>
      <webElementGuid>9fa1e776-35c4-407c-9293-4ff59ee09b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>f79ce3d3-40b9-4657-b2b8-35f4bb66b177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>42ad598e-0c39-4cf1-834e-a957486fb95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-4115-btnIconEl&quot;)</value>
      <webElementGuid>e4925232-9f2d-4041-8cec-2c1df62486c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-4115-btnIconEl']</value>
      <webElementGuid>ed5e7439-3234-4da5-8e29-123f943a773d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-4115-btnEl']/span[2]</value>
      <webElementGuid>d3655adc-ea69-4c81-91f0-8c094bbe9397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a/span/span/span[2]</value>
      <webElementGuid>f388b080-bdda-47ae-97fd-be237c603337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-4115-btnIconEl']</value>
      <webElementGuid>def6cc54-e4d8-49fd-a6ea-0b5f25b7cc96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
