<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fraude_button-4145-btnIconEl</name>
   <tag></tag>
   <elementGuidId>28a60ffc-33a7-4e8e-9cfb-42b4a38c4894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-4145-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-4145-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d7cee36-d14c-403a-9e70-a4325799abd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9410298-0fd4-4f3f-ba4a-507f8907b144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-4145-btnIconEl</value>
      <webElementGuid>dff3844e-0939-4a01-ab88-61fa8bdbaed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>71736b09-5bf8-4766-9d4c-46edb4a3134a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>41e9235d-8d0e-4736-8266-36e964df797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-4145-btnIconEl&quot;)</value>
      <webElementGuid>d6c40485-daf1-4a15-9a19-90cba42a97c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-4145-btnIconEl']</value>
      <webElementGuid>f0f25bfa-1eb3-400e-8f64-4c6f81e0bc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-4145-btnEl']/span[2]</value>
      <webElementGuid>f1768fd1-0ace-4edb-9fda-5101f2e73b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]/div/div/a[4]/span/span/span[2]</value>
      <webElementGuid>f25bb109-9f1e-41d9-8d49-f9a656e91a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-4145-btnIconEl']</value>
      <webElementGuid>69c2cf9a-ffb2-4d7c-a1b1-c7bc99b2b657</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
