<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_X - Cerrar_button-2351-btnIconEl</name>
   <tag></tag>
   <elementGuidId>45812cfc-b059-403b-800f-3acdd8141451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-2351-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-2351-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90a4ec41-eb71-4b81-91f0-0b87c005c5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e2f7fba-33e0-4388-87be-a5e9ac5389b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-2351-btnIconEl</value>
      <webElementGuid>b5c75f3a-314c-40aa-800a-9b7b7154b3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>7eaf98bd-afad-4dfa-b0cd-e9ceaadee940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4452dd03-903a-45e3-ab03-396591b9cda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-2351-btnIconEl&quot;)</value>
      <webElementGuid>eb16f67e-5038-4690-875e-2fbb9ece92e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-2351-btnIconEl']</value>
      <webElementGuid>ef0e1c7a-6205-45fa-b454-810508a1bbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-2351-btnEl']/span[2]</value>
      <webElementGuid>d8bbdc49-1078-44b1-9288-3cd465b8ef7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a/span/span/span[2]</value>
      <webElementGuid>6e3f56d7-5625-4c7a-b9a5-4a068b440aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-2351-btnIconEl']</value>
      <webElementGuid>7fdc6d4e-aab8-401b-88da-c6b70f978339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
