<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fraude_button-5909-btnIconEl</name>
   <tag></tag>
   <elementGuidId>20e56e84-78fa-407f-a87f-466d08f79f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-5909-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-5909-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0cf264ac-7b2e-4ab7-9e0b-6a514e47165e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8bfe9369-86a3-4ff8-84f5-6e40cb5b0433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-5909-btnIconEl</value>
      <webElementGuid>353e9332-f813-48bf-b1d9-70f8906a2514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>95670d53-abfd-4a73-adec-bdb614bbf727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>9fe82a35-5a72-4a08-9b99-0020c93b6cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-5909-btnIconEl&quot;)</value>
      <webElementGuid>e91b86d5-f8ba-4004-b146-a1aaf071fd40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-5909-btnIconEl']</value>
      <webElementGuid>4c5db8f3-9831-4335-8363-3f4fcff34e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-5909-btnEl']/span[2]</value>
      <webElementGuid>be3d9193-3177-4e74-ba73-345aa575dadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]/div/div/a[4]/span/span/span[2]</value>
      <webElementGuid>3d3f2b54-8bd1-4e8e-bdf1-99505d37d25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-5909-btnIconEl']</value>
      <webElementGuid>ac002881-60fb-40b1-8e4a-3026dcd04cc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
